services:
  - type: web
    name: video-bot-api
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -c "from database import init_db; import asyncio; asyncio.run(init_db())"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - key: ENV
        value: prod
      - key: TELEGRAM_TOKEN
        value: ${TELEGRAM_TOKEN}